// AddEventDialog.h


#pragma once
#include <QDialog>
#include "TimelineModel.h"


// Forward declaration of the UI class generated by Qt's uic from AddEventDialog.ui
// This follows the Qt Designer integration pattern for separating UI from logic
namespace Ui {
class AddEventDialog;
}


/**
 * @class AddEventDialog
 * @brief Dialog for creating new timeline events
 *
 * Provides a form-based UI for entering all event details :
 * - Type               (dropdown)
 * - Title              (text input)
 * - Start/End dates    (date pickers)
 * - Description        (multiline text)
 * - Priority           (spinner)
 *
 * The dialog enforces validation rules:
 * - Title must not be empty
 * - Start date must be <= end date
 * - Dates must fall within the version boundary dates
 *
 * UI is designed in Qt Designer (.ui file) and connected via the Ui:: namespace.
 */
class AddEventDialog : public QDialog
{
    Q_OBJECT

public:
    /**
     * @brief Construct the AddEventDialog with version date boundaries
     * @param versionStart Earliest allowed date for events (version start date)
     * @param versionEnd Latest allowed date for events (version end date)
     * @param parent Parent widget for proper Qt memory management
     *
     * The constructor initializes the UI from the .ui file, configures date
     * range constraints, and connects all signal-slot interactions.
     */
    explicit AddEventDialog(const QDate& versionStart,
                            const QDate& versionEnd,
                            QWidget* parent = nullptr);

    /**
     * @brief Destructor - cleans up the UI pointer
     *
     * Deletes the Ui::AddEventDialog instance created during construction.
     */
    ~AddEventDialog();

    /**
     * @brief Retrieve the constructed TimelineObject from dialog inputs
     * @return TimelineObject populated with user-entered data
     *
     * This method should only be called after the dialog is accepted (exec() returns
     * QDialog::Accepted). It extracts all form values and constructs a complete
     * TimelineObject ready to be added to the model.
     *
     * The ID field is left empty; the model will assign a unique ID.
     * The color is determined by the TimelineModel based on the selected type.
     */
    TimelineEvent getEvent() const;

private slots:
    /**
     * @brief Validate all user inputs before accepting the dialog
     *
     * Performs validation checks:
     * - Title must not be empty or whitespace-only
     * - Start date must be <= end date
     *
     * If validation fails, displays a warning message and keeps the dialog open.
     * If validation succeeds, calls accept() to close the dialog with QDialog::Accepted.
     */
    void validateAndAccept();

    /**
     * @brief Handler for start date changes to maintain date consistency
     * @param date The newly selected start date
     *
     * When the user changes the start date, this slot ensures that:
     * - The end date cannot be earlier than the new start date
     * - If the current end date is now invalid, it is automatically adjusted
     *
     * This prevents invalid date ranges from being created during user interaction.
     */
    void onStartDateChanged(const QDate& date);

private:
    Ui::AddEventDialog* ui;  ///< Pointer to the UI class generated from AddEventDialog.ui
    QDate versionStart_;     ///< Version start date boundary for validation
    QDate versionEnd_;       ///< Version end date boundary for validation
};
