// ScrollToDateDialog.h


#pragma once
#include <QDialog>
#include <QDate>


// Forward declaration of UI class generated by Qt Designer
namespace Ui {
class ScrollToDateDialog;
}


/**
 * @class ScrollToDateDialog
 * @brief Dialog for smart scroll-to-date functionality
 *
 * UI is designed in Qt Designer (ScrollToDateDialog.ui)
 *
 * Provides:
 * - Date picker for target date
 * - Option to animate scroll
 * - Option to highlight date range
 */
class ScrollToDateDialog : public QDialog
{
    Q_OBJECT

public:
    /**
     * @brief Construct scroll-to-date dialog
     * @param currentDate Initial date to show in picker
     * @param minDate Minimum selectable date (version start)
     * @param maxDate Maximum selectable date (version end)
     * @param parent Parent widget
     */
    explicit ScrollToDateDialog(const QDate& currentDate,
                                const QDate& minDate,
                                const QDate& maxDate,
                                QWidget* parent = nullptr);

    /**
     * @brief Destructor - cleans up UI
     */
    ~ScrollToDateDialog();

    /**
     * @brief Get selected target date
     */
    QDate targetDate() const;

    /**
     * @brief Check if smooth animation is requested
     */
    bool shouldAnimate() const;

    /**
     * @brief Check if date should be highlighted after scroll
     */
    bool shouldHighlight() const;

    /**
     * @brief Get highlight range in days (before and after target)
     */
    int highlightRangeDays() const;

private slots:
    /**
     * @brief Handle highlight checkbox toggle
     */
    void onHighlightToggled(bool checked);

private:
    /**
     * @brief Setup signal/slot connections
     */
    void setupConnections();

    Ui::ScrollToDateDialog* ui;     ///< UI class generated from .ui file
    QDate currentDate_;
    QDate minDate_;
    QDate maxDate_;
};
