// VersionSettingsDialog.h
// Qt Designer Integration Version


#pragma once
#include <QDialog>
#include <QDate>


// Forward declaration of the UI class generated by Qt Designer
// This is automatically generated from VersionSettingsDialog.ui
namespace Ui
{
    class VersionSettingsDialog;
}


/**
 * @class VersionSettingsDialog
 * @brief Dialog for setting timeline version start and end dates
 *
 * This dialog is designed in Qt Designer and provides:
 * - Version name input (optional)
 * - Start date picker with calendar popup
 * - End date picker with calendar popup
 * - Automatic validation (start <= end)
 * - Date range constraints
 *
 * Usage:
 * @code
 * VersionSettingsDialog dialog(currentStart, currentEnd, this);
 * if (dialog.exec() == QDialog::Accepted) {
 *     QDate newStart = dialog.startDate();
 *     QDate newEnd = dialog.endDate();
 *     QString name = dialog.versionName();
 *     // Update model...
 * }
 * @endcode
 */
class VersionSettingsDialog : public QDialog
{
    Q_OBJECT

public:
    /**
     * @brief Construct dialog with current version dates
     * @param currentStart Current version start date
     * @param currentEnd Current version end date
     * @param parent Parent widget for Qt memory management
     */
    explicit VersionSettingsDialog(const QDate& currentStart,
                                   const QDate& currentEnd,
                                   QWidget* parent = nullptr);

    /**
     * @brief Destructor - cleans up UI
     */
    ~VersionSettingsDialog();

    /**
     * @brief Get the selected start date
     * @return Start date from date picker
     */
    QDate startDate() const;

    /**
     * @brief Get the selected end date
     * @return End date from date picker
     */
    QDate endDate() const;

    /**
     * @brief Get the version name (optional field)
     * @return Version name string (may be empty)
     */
    QString versionName() const;

private slots:
    /**
     * @brief Validate all inputs before accepting dialog
     *
     * Checks:
     * - Start date <= end date
     * - Date range is reasonable (warns if < 1 week)
     *
     * If validation fails, keeps dialog open and shows warning.
     * If validation succeeds, accepts dialog.
     */
    void validateAndAccept();

    /**
     * @brief Handle start date changes to maintain consistency
     * @param date New start date
     *
     * When start date changes:
     * - Updates end date minimum to match start date
     * - Auto-adjusts end date if now invalid
     */
    void onStartDateChanged(const QDate& date);

private:
    /**
     * @brief Setup signal/slot connections
     *
     * Connects:
     * - OK button → validateAndAccept()
     * - Cancel button → reject()
     * - Start date changes → onStartDateChanged()
     */
    void setupConnections();

    Ui::VersionSettingsDialog* ui;      ///< UI class generated from .ui file
    QDate currentStart_;                ///< Original start date (for reference)
    QDate currentEnd_;                  ///< Original end date (for reference)
};
